{% set meta_data = load_setup_py_data() %}
{% set core_data = load_setup_py_data(setup_file='marbles/core/setup.py') %}
{% set mixins_data = load_setup_py_data(setup_file='marbles/mixins/setup.py') %}

package:
  name: marbles
  version: {{ meta_data.get('version') }}

source:
  git_url: ../

build:
  number: 0

requirements:
  build:
    - coverage
    - flake8
    - python
    - setuptools
    - sphinx
    - sphinx_rtd_theme
  run:
    - marbles-core
    - marbles-mixins
  test:
    imports:
      - marbles.core
      - marbles.core.marbles
      - marbles.core.log
      - marbles.mixins

outputs:
  - name: marbles-core
    version: {{ core_data.get('version') }}
    script: marbles-core.sh
    requirements:

  - name: marbles-mixins
    version: {{ mixins_data.get('version') }}
    script: marbles-mixins.sh
    requirements:
      - pandas <0.21,>=0.19.1
      - numpy <1.14,>=1.12.1

about:
  home: https://github.com/twosigma/marbles
  summary: Write better tests, read better test failures
